languageCode = "en"
languageName = "English"
weight = 1
title="Guides.md"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  # secondaryLogo = "PATH"
  description = ""
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Guides.md"
  image = "img/blowfish_logo.png"
  headline = "A curated collections of immersive guides,"
  # bio = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  # links = [
  #   { twitter = "https://twitter.com/burufugu" },
  #   { mastodon = "https://masto.ai/@blowfish" },
  #   { github = "https://github.com/nunocoracao/blowfish" },
  # ]

  